### ISSUE TITLE
set up travis-ci linting/unit tests

### ISSUE THREAD

**Issue by guykisel** [midniteio/multi-cuke#2]

**Comment by midniteio** [comment]
Resolved in https://github.com/midniteio/multi-cuke/commit/3cd271d207bfbfec50a495c383c0ff02fda1eae4 and https://github.com/midniteio/multi-cuke/commit/b67ce631a4d8561da0c8ebdf36c88079868dc616.

Unit test/Linting both enabled in travis-ci via npm test in 0.3.0
