### ISSUE TITLE
workers cannot exceed number of cores

### ISSUE THREAD

**Issue by jimusbobus** [midniteio/multi-cuke#35]
Passing the argument to the cli of -w 8 does not run 8 tests in parallel, I even tried editing the .js files for main and cli and hard coded the worker defaults to 8 but still only 4 are run.  

Should setting the -w argument allow more than 4 to be run?

Thanks

**Comment by jimusbobus** [comment]
oops sorry,  i discovered the max workers, all good :)

**Comment by midniteio** [comment]
@jimusbobus we could probably lift the workers cap, though one worker per core seemed like the right call for parallelization. Thinking on this now, it does feel off to accept a value for workers but then not use it in favor of CPU core limit (i.e. if you want to run 20 in parallel, and explicitly pass it, then we should provide the ability for you to do that, regardless of whether it works well/is effective 😆). Will open a PR to pull this limit out.

**Comment by midniteio** [comment]
This is resolved now in `0.8.4`, thanks for the ticket!
