### ISSUE TITLE
Can't identify feature tags

### ISSUE THREAD

**Issue by guilhotarras** [midniteio/multi-cuke#63]
When having a feature:

@BAT_file
Feature: CPA BAT

  @01_web_app_build_number
  Scenario: BAT 01 -  Web App Build Number
    Given I am on CPA Login page
    And I should be at "LOGIN PAGE"
    And I login with "BAT ACCOUNT"

and having this configuration:

const multicuke = require('multi-cuke').default;
var options = {
    paths: ['./features'],
    tags: ['@BAT_file'],
    requires: [],
    cucumberPath: "node_modules/cucumber/bin/cucumber.js",
    workers: 4,
    workerEnvVars: {},
    logDir: '.multiCuke_logs',
    silentSummary: false,
    verbose: false,
    inlineStream: false,
    failFast: false,
    devMode: false,
    strict: false
};
multicuke(options);

multi-cuke throws this message: There are no scenarios found that match the options passed.

So, I assume that feature tags are being ignored

**Comment by midniteio** [comment]
Interesting. Let me look at how this is getting parsed out.

As an aside, feel free to also jump into gitter, there's a multi-cuke lobby that's setup. If you have any questions off the cuff I'd be happy to answer there as well.

**Comment by midniteio** [comment]
This is resolved in `0.13.4`
