### ISSUE TITLE
JSON output file

### ISSUE THREAD

**Issue by guilhotarras** [midniteio/multi-cuke#64]
Is there any way to generate a json output format for the test execution ?

**Comment by midniteio** [comment]
We could certainly implement that, adding label for now and will look at getting that in.

**Comment by midniteio** [comment]
There is a `--logdir` flag That you can pass a path to, thats where json logs end up.

You can see the cucumber command that gets run here, we always export a json file actually, it's what we use to parse the results per-scenario and then aggregate for results https://github.com/midniteio/multi-cuke/blob/master/src/lib/worker.js#L35

Also, all the scenarios do get merged back into a single results json file here once all are finished https://github.com/midniteio/multi-cuke/blob/master/src/lib/test-handler.js#L76

So this should provide the granularity of individual logs and a single overall log
